[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = '0.8.27'
evm_version = 'shanghai'
optimizer = true
optimizer_runs = 200
via_ir = true
ffi = false                                               # false by default for security reasons
fs_permissions = [{ access = "read-write", path = "./" }]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
